name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: List all Files
        run: ls -a

      - name: Print Working Directory
        run: pwd

      - name: Create Js File
        run: echo 'console.log("hello");' > app.js

      - name: Run Node.js File
        run: node app.js
